# Generated by Django 3.2.15 on 2023-10-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mappoint',
            options={'verbose_name': 'локация', 'verbose_name_plural': 'локации'},
        ),
    ]
