# Generated by Django 3.2.15 on 2023-10-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_mappoint_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='address',
            field=models.CharField(max_length=200, unique=True, verbose_name='адрес'),
        ),
    ]
