# Generated by Django 3.2.15 on 2023-10-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_alter_mappoint_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MapPoint',
            new_name='Address',
        ),
    ]
