# Generated by Django 3.2.15 on 2023-09-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0003_rename_product_orderitem_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
