# Generated by Django 3.2.15 on 2023-09-18 09:08

from django.db import migrations
from ..models import OrderItem


def calculate_order_item_price(apps, schema_editor):
    order_items = OrderItem.objects.all()
    for item in order_items:
        item.price = item.quantity * item.product.price
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0005_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(calculate_order_item_price)
    ]
