# Generated by Django 3.2.15 on 2023-09-21 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0006_auto_20230918_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('MANAGER', 'Менеджер'), ('RESTAURANT', 'Ресторан'), ('COURIER', 'Курьер'), ('COMPLETED', 'Выполнен')], default='MANAGER', max_length=10, verbose_name='статус заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
