# Generated by Django 3.2.15 on 2023-09-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0010_auto_20230922_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('MANAGER', 'Необработанный'), ('RESTAURANT', 'В ресторане'), ('COURIER', 'У курьера'), ('COMPLETED', 'Выполнен')], db_index=True, default='MANAGER', max_length=10, verbose_name='статус заказа'),
        ),
    ]
