# Generated by Django 3.2.15 on 2023-09-22 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0011_auto_20230922_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличный'), ('NON_CASH', 'Безналичный')], db_index=True, default='CASH', max_length=15, verbose_name='способ оплаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='время создания заказа'),
        ),
    ]
