# Generated by Django 3.2.15 on 2023-09-30 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0013_order_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='order',
            name='available_restaurants',
            field=models.CharField(default='', max_length=200, verbose_name='доступные рестораны'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cooking_restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='готовится в ресторане'),
        ),
    ]
