# Generated by Django 3.2.15 on 2023-10-02 08:54
import requests
from django.db import migrations
from ..models import Restaurant
from django.conf import settings


apikey = settings.GEOCODER_API_KEY


def fetch_coordinates(apikey, address):
    base_url = "https://geocode-maps.yandex.ru/1.x"
    response = requests.get(base_url, params={
        "geocode": address,
        "apikey": apikey,
        "format": "json",
    })
    response.raise_for_status()
    found_places = response.json()['response']['GeoObjectCollection']['featureMember']

    most_relevant = found_places[0]
    lon, lat = most_relevant['GeoObject']['Point']['pos'].split(" ")
    return lon, lat


def determine_restaurant_coordinates(apps, schema_editor):
    restaurants = Restaurant.objects.all()
    for restaurant in restaurants:
        (lon, lat) = fetch_coordinates(apikey, restaurant.address)
        restaurant.lon = lon
        restaurant.lat = lat
        restaurant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0016_auto_20231001_1731'),
    ]

    operations = [
        migrations.RunPython(determine_restaurant_coordinates)
    ]
